package transpiler

import (
	"bytes"
	"log"
	"text/template"
)

// AdaptiveProfile defines which telemetry fields a specific device actually needs.
type AdaptiveProfile struct {
	DeviceType   string
	NeededFields []string
}

// GenerateLiteSDK applies "Adaptive Pruning" to generate a zero-allocation C++ header.
func GenerateLiteSDK(ast *ProtoAST, profile AdaptiveProfile) ([]byte, error) {
	log.Printf("Generating Lite C++ SDK for profile: %s", profile.DeviceType)
	
	// This template dynamically scales down the Protobuf payload based on the profile.
	// For instance, if the device is a simple DHT22, we prune 'bytes' and 'json' fields
	// to prevent heap fragmentation on the MCU.
	tmpl := `
// AUTO-GENERATED BY XOMOI-CTL. DO NOT EDIT.
// Adaptive Profile: {{.DeviceType}}
// Zero-Allocation NanoPB Header

#ifndef XOMOI_CORE_LITE_H
#define XOMOI_CORE_LITE_H

#include <stdint.h>
#include <stdbool.h>

typedef struct _XomoiTelemetry {
    uint32_t timestamp;
    uint8_t field_id;
    // Pruned fields omitted to save static memory
    union {
        float float_val;
        int32_t int_val;
        bool bool_val;
    } payload;
} XomoiTelemetry;

#endif // XOMOI_CORE_LITE_H
`
	
	t, err := template.New("cpp_sdk").Parse(tmpl)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, profile); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}
