// Xomoi-Core: Sovereign Edge Node
// Copyright (C) 2026 Adrish Bora (@code-grey) & Simanjit Hujuri (@code-zephyrus)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AlertRule struct {
	ID        string       `json:"id"`
	DeviceID  string       `json:"device_id"`
	TagName   string       `json:"tag_name"`
	Condition string       `json:"condition"`
	Threshold float64      `json:"threshold"`
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Device struct {
	ID         string       `json:"id"`
	Name       string       `json:"name"`
	MacAddress string       `json:"mac_address"`
	SecretKey  string       `json:"secret_key"`
	LastSeen   sql.NullTime `json:"last_seen"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type SensorTag struct {
	DeviceID string `json:"device_id"`
	FieldID  int64  `json:"field_id"`
	TagName  string `json:"tag_name"`
	DataType string `json:"data_type"`
}

type Session struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Telemetry struct {
	DeviceID  string          `json:"device_id"`
	Timestamp time.Time       `json:"timestamp"`
	Payload   json.RawMessage `json:"payload"`
}

type TelemetryHistory struct {
	ID          int64           `json:"id"`
	DeviceID    string          `json:"device_id"`
	Temperature sql.NullFloat64 `json:"temperature"`
	Humidity    sql.NullFloat64 `json:"humidity"`
	State       sql.NullString  `json:"state"`
	Timestamp   sql.NullTime    `json:"timestamp"`
}

type TelemetryRollup struct {
	DeviceID   string          `json:"device_id"`
	Date       time.Time       `json:"date"`
	AvgPayload json.RawMessage `json:"avg_payload"`
	MaxPayload json.RawMessage `json:"max_payload"`
	MinPayload json.RawMessage `json:"min_payload"`
}

type User struct {
	ID           string       `json:"id"`
	Username     string       `json:"username"`
	PasswordHash string       `json:"password_hash"`
	Role         string       `json:"role"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type UserDeviceRole struct {
	UserID   string `json:"user_id"`
	DeviceID string `json:"device_id"`
	Role     string `json:"role"`
}
