// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql"
	"encoding/json"
	"time"
)

type AlertRule struct {
	ID        string       `json:"id"`
	DeviceID  string       `json:"device_id"`
	TagName   string       `json:"tag_name"`
	Condition string       `json:"condition"`
	Threshold float64      `json:"threshold"`
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Device struct {
	ID         string       `json:"id"`
	Name       string       `json:"name"`
	MacAddress string       `json:"mac_address"`
	SecretKey  string       `json:"secret_key"`
	LastSeen   sql.NullTime `json:"last_seen"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

type SensorTag struct {
	DeviceID string `json:"device_id"`
	FieldID  int64  `json:"field_id"`
	TagName  string `json:"tag_name"`
	DataType string `json:"data_type"`
}

type Session struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	TokenHash string       `json:"token_hash"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Telemetry struct {
	DeviceID  string          `json:"device_id"`
	Timestamp time.Time       `json:"timestamp"`
	Payload   json.RawMessage `json:"payload"`
}

type TelemetryRollup struct {
	DeviceID   string          `json:"device_id"`
	Date       time.Time       `json:"date"`
	AvgPayload json.RawMessage `json:"avg_payload"`
	MaxPayload json.RawMessage `json:"max_payload"`
	MinPayload json.RawMessage `json:"min_payload"`
}

type User struct {
	ID           string       `json:"id"`
	Username     string       `json:"username"`
	PasswordHash string       `json:"password_hash"`
	Role         string       `json:"role"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type UserDeviceRole struct {
	UserID   string `json:"user_id"`
	DeviceID string `json:"device_id"`
	Role     string `json:"role"`
}
