// Xomoi-Core: Sovereign Edge Node
// Copyright (C) 2026 Adrish Bora (@code-grey) & Simanjit Hujuri (@code-zephyrus)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package dbgen

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    id, name, mac_address, secret_key
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, name, mac_address, secret_key, last_seen, created_at
`

type CreateDeviceParams struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	MacAddress string `json:"mac_address"`
	SecretKey  string `json:"secret_key"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice,
		arg.ID,
		arg.Name,
		arg.MacAddress,
		arg.SecretKey,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MacAddress,
		&i.SecretKey,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRawTelemetryBefore = `-- name: DeleteRawTelemetryBefore :exec
DELETE FROM telemetry
WHERE date(timestamp) < ?
`

func (q *Queries) DeleteRawTelemetryBefore(ctx context.Context, timestamp time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteRawTelemetryBefore, timestamp)
	return err
}

const getDeviceByMAC = `-- name: GetDeviceByMAC :one
SELECT id, name, mac_address, secret_key, last_seen, created_at FROM devices
WHERE mac_address = ? LIMIT 1
`

func (q *Queries) GetDeviceByMAC(ctx context.Context, macAddress string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByMAC, macAddress)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MacAddress,
		&i.SecretKey,
		&i.LastSeen,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceRoles = `-- name: GetDeviceRoles :many
SELECT u.username, r.role
FROM user_device_roles r
JOIN users u ON u.id = r.user_id
WHERE r.device_id = ?
`

type GetDeviceRolesRow struct {
	Username string `json:"username"`
	Role     string `json:"role"`
}

func (q *Queries) GetDeviceRoles(ctx context.Context, deviceID string) ([]GetDeviceRolesRow, error) {
	rows, err := q.db.QueryContext(ctx, getDeviceRoles, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeviceRolesRow
	for rows.Next() {
		var i GetDeviceRolesRow
		if err := rows.Scan(&i.Username, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTelemetryHistory = `-- name: GetTelemetryHistory :many
SELECT id, device_id, temperature, humidity, state, timestamp FROM telemetry_history
WHERE device_id = ? 
  AND timestamp >= ?
ORDER BY timestamp ASC
`

type GetTelemetryHistoryParams struct {
	DeviceID  string       `json:"device_id"`
	Timestamp sql.NullTime `json:"timestamp"`
}

func (q *Queries) GetTelemetryHistory(ctx context.Context, arg GetTelemetryHistoryParams) ([]TelemetryHistory, error) {
	rows, err := q.db.QueryContext(ctx, getTelemetryHistory, arg.DeviceID, arg.Timestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelemetryHistory
	for rows.Next() {
		var i TelemetryHistory
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Temperature,
			&i.Humidity,
			&i.State,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTelemetry = `-- name: InsertTelemetry :exec
INSERT INTO telemetry_history (
    device_id, temperature, humidity, state
) VALUES (
    ?, ?, ?, ?
)
`

type InsertTelemetryParams struct {
	DeviceID    string          `json:"device_id"`
	Temperature sql.NullFloat64 `json:"temperature"`
	Humidity    sql.NullFloat64 `json:"humidity"`
	State       sql.NullString  `json:"state"`
}

func (q *Queries) InsertTelemetry(ctx context.Context, arg InsertTelemetryParams) error {
	_, err := q.db.ExecContext(ctx, insertTelemetry,
		arg.DeviceID,
		arg.Temperature,
		arg.Humidity,
		arg.State,
	)
	return err
}

const insertTelemetryRollup = `-- name: InsertTelemetryRollup :exec
INSERT INTO telemetry_rollups (
    device_id, date, avg_payload, max_payload, min_payload
) VALUES (
    ?, ?, ?, ?, ?
)
ON CONFLICT(device_id, date) DO UPDATE SET
    avg_payload = excluded.avg_payload,
    max_payload = excluded.max_payload,
    min_payload = excluded.min_payload
`

type InsertTelemetryRollupParams struct {
	DeviceID   string          `json:"device_id"`
	Date       time.Time       `json:"date"`
	AvgPayload json.RawMessage `json:"avg_payload"`
	MaxPayload json.RawMessage `json:"max_payload"`
	MinPayload json.RawMessage `json:"min_payload"`
}

func (q *Queries) InsertTelemetryRollup(ctx context.Context, arg InsertTelemetryRollupParams) error {
	_, err := q.db.ExecContext(ctx, insertTelemetryRollup,
		arg.DeviceID,
		arg.Date,
		arg.AvgPayload,
		arg.MaxPayload,
		arg.MinPayload,
	)
	return err
}

const pruneTelemetryHistory = `-- name: PruneTelemetryHistory :exec
DELETE FROM telemetry_history
WHERE timestamp < datetime('now', '-30 days')
`

func (q *Queries) PruneTelemetryHistory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, pruneTelemetryHistory)
	return err
}

const upsertUserDeviceRole = `-- name: UpsertUserDeviceRole :exec
INSERT INTO user_device_roles (
    user_id, device_id, role
) VALUES (
    ?, ?, ?
)
ON CONFLICT(user_id, device_id) DO UPDATE SET
    role = excluded.role
`

type UpsertUserDeviceRoleParams struct {
	UserID   string `json:"user_id"`
	DeviceID string `json:"device_id"`
	Role     string `json:"role"`
}

func (q *Queries) UpsertUserDeviceRole(ctx context.Context, arg UpsertUserDeviceRoleParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserDeviceRole, arg.UserID, arg.DeviceID, arg.Role)
	return err
}
