// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
	"time"
)

type Querier interface {
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	DeleteRawTelemetryBefore(ctx context.Context, timestamp time.Time) error
	GetDeviceByMAC(ctx context.Context, macAddress string) (Device, error)
	GetDeviceRoles(ctx context.Context, deviceID string) ([]GetDeviceRolesRow, error)
	GetTelemetryHistory(ctx context.Context, arg GetTelemetryHistoryParams) ([]TelemetryHistory, error)
	InsertTelemetry(ctx context.Context, arg InsertTelemetryParams) error
	InsertTelemetryRollup(ctx context.Context, arg InsertTelemetryRollupParams) error
	PruneTelemetryHistory(ctx context.Context) error
	UpsertUserDeviceRole(ctx context.Context, arg UpsertUserDeviceRoleParams) error
}

var _ Querier = (*Queries)(nil)
