// Xomoi-Core: Sovereign Edge Node
// Copyright (C) 2026 Adrish Bora (@code-grey) & Simanjit Hujuri (@code-zephyrus)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
	"time"
)

type Querier interface {
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	DeleteRawTelemetryBefore(ctx context.Context, timestamp time.Time) error
	GetDeviceByMAC(ctx context.Context, macAddress string) (Device, error)
	GetDeviceRoles(ctx context.Context, deviceID string) ([]GetDeviceRolesRow, error)
	GetTelemetryHistory(ctx context.Context, arg GetTelemetryHistoryParams) ([]TelemetryHistory, error)
	InsertTelemetry(ctx context.Context, arg InsertTelemetryParams) error
	InsertTelemetryRollup(ctx context.Context, arg InsertTelemetryRollupParams) error
	PruneTelemetryHistory(ctx context.Context) error
	UpsertUserDeviceRole(ctx context.Context, arg UpsertUserDeviceRoleParams) error
}

var _ Querier = (*Queries)(nil)
